#!/usr/bin/env bash
#
# Provision a fresh Hetzner / Ubuntu 24.04 box for Ocean Quest.
#
#   sudo bash deploy/setup.sh ocean-quest
#
# Idempotent — safe to re-run. Designed to be re-run for *future* projects
# on the same box (different project name → different /opt/projects/<name>,
# different Linux user, different Postgres DB and roles).
#
# What it does:
#   1. Installs Postgres 16, Caddy, Python 3, build deps, ufw
#   2. Creates Linux user `<project>` with home /opt/projects/<project>
#   3. Creates Postgres DB `<project_underscored>` plus
#      `<project>_rw` (read+write) and `<project>_ro` (read-only) roles
#   4. Configures Postgres to listen publicly with SSL forced
#      (drops in deploy/postgresql/*.snippet)
#   5. Generates a self-signed cert for SSL (replace with Let's Encrypt
#      via Caddy's pgsql.io_lib if you ever want a real cert)
#   6. Creates Python venv, installs requirements
#   7. Drops in systemd units, runs `db.py init`, enables and starts services
#   8. Opens UFW for 22 (SSH), 80, 443 (Caddy for future projects), 5432 (Postgres)
#
# The script reads the project source from the current git checkout — clone
# the repo to /opt/projects/<project> first, then run this from inside it.

set -euo pipefail

PROJECT="${1:-}"
if [ -z "$PROJECT" ]; then
    echo "Usage: $0 <project-name>"
    echo "Example: $0 ocean-quest"
    exit 1
fi

# Postgres role/db names can't have hyphens — convert to underscore.
DBNAME="${PROJECT//-/_}"
RW_ROLE="${DBNAME}_rw"
RO_ROLE="${DBNAME}_ro"
PROJECT_DIR="/opt/projects/${PROJECT}"
ETC_DIR="/etc/${PROJECT}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==> Project:        $PROJECT"
echo "==> Linux user:     $PROJECT"
echo "==> Project dir:    $PROJECT_DIR"
echo "==> Postgres DB:    $DBNAME"
echo "==> Roles:          $RW_ROLE (rw), $RO_ROLE (ro)"
echo

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: must be run as root (use sudo)"; exit 1
fi

# ── 1. APT packages ────────────────────────────────────────────────────
echo "==> Installing system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
    postgresql-16 postgresql-contrib-16 \
    python3 python3-venv python3-pip \
    build-essential libpq-dev \
    ufw curl debian-keyring debian-archive-keyring apt-transport-https

# Caddy (kept ready for future projects' frontends)
if ! command -v caddy >/dev/null 2>&1; then
    echo "==> Installing Caddy..."
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update
    apt-get install -y caddy
fi

# ── 2. Linux user + project directory ───────────────────────────────────
if ! id -u "$PROJECT" >/dev/null 2>&1; then
    echo "==> Creating Linux user $PROJECT..."
    useradd --system --create-home --home-dir "$PROJECT_DIR" \
            --shell /usr/sbin/nologin "$PROJECT"
fi
mkdir -p "$PROJECT_DIR"
chown -R "$PROJECT:$PROJECT" "$PROJECT_DIR"

# ── 3. /etc/<project>/env ──────────────────────────────────────────────
mkdir -p "$ETC_DIR"
chmod 750 "$ETC_DIR"
chown root:"$PROJECT" "$ETC_DIR"

if [ ! -f "$ETC_DIR/env" ]; then
    RW_PASSWORD="$(openssl rand -hex 24)"
    RO_PASSWORD="$(openssl rand -hex 24)"
    cat > "$ETC_DIR/env" <<EOF
# Generated by deploy/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ROBLOX_API_KEY=PUT_YOUR_KEY_HERE
ROBLOX_UNIVERSE_ID=PUT_YOUR_UNIVERSE_ID_HERE
DATABASE_URL=postgresql://${RW_ROLE}:${RW_PASSWORD}@localhost/${DBNAME}
EOF
    chmod 640 "$ETC_DIR/env"
    chown root:"$PROJECT" "$ETC_DIR/env"
    echo "==> Wrote $ETC_DIR/env  (EDIT THIS to set ROBLOX_API_KEY + ROBLOX_UNIVERSE_ID)"
    echo
    echo "    READ-ONLY connection string for Streamlit Cloud:"
    PUBLIC_IP="$(curl -s4 ifconfig.me || echo HETZNER_PUBLIC_IP)"
    echo "    postgresql://${RO_ROLE}:${RO_PASSWORD}@${PUBLIC_IP}:5432/${DBNAME}?sslmode=require"
    echo
    # Stash the RO password so we can SET PASSWORD below
    echo "$RO_PASSWORD" > "$ETC_DIR/.ro_password.tmp"
    chmod 600 "$ETC_DIR/.ro_password.tmp"
else
    echo "==> $ETC_DIR/env already exists; leaving it alone."
fi

# Pull the RW password back out of the env file so we can set it on the role
RW_PASSWORD="$(grep -oP '(?<=://[^:]+:)[^@]+(?=@localhost/)' "$ETC_DIR/env")"

# ── 4. Postgres DB + roles ─────────────────────────────────────────────
echo "==> Creating Postgres DB and roles (idempotent)..."
sudo -u postgres psql <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${RW_ROLE}') THEN
        CREATE ROLE ${RW_ROLE} LOGIN PASSWORD '${RW_PASSWORD}';
    ELSE
        ALTER ROLE ${RW_ROLE} WITH PASSWORD '${RW_PASSWORD}';
    END IF;
END\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DBNAME}') THEN
        CREATE DATABASE ${DBNAME} OWNER ${RW_ROLE};
    END IF;
END\$\$;
SQL

if [ -f "$ETC_DIR/.ro_password.tmp" ]; then
    RO_PASSWORD="$(cat "$ETC_DIR/.ro_password.tmp")"
    sudo -u postgres psql <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${RO_ROLE}') THEN
        CREATE ROLE ${RO_ROLE} LOGIN PASSWORD '${RO_PASSWORD}';
    ELSE
        ALTER ROLE ${RO_ROLE} WITH PASSWORD '${RO_PASSWORD}';
    END IF;
END\$\$;
GRANT CONNECT ON DATABASE ${DBNAME} TO ${RO_ROLE};
SQL
    sudo -u postgres psql -d "$DBNAME" <<SQL
GRANT USAGE ON SCHEMA public TO ${RO_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO ${RO_ROLE};
SQL
    rm -f "$ETC_DIR/.ro_password.tmp"
fi

# ── 5. Postgres config: listen externally, SSL on ──────────────────────
PGCONF="/etc/postgresql/16/main/postgresql.conf"
PGHBA="/etc/postgresql/16/main/pg_hba.conf"
SSL_DIR="/etc/postgresql/16/main"

if [ ! -f "${SSL_DIR}/server.crt" ]; then
    echo "==> Generating self-signed Postgres SSL cert..."
    openssl req -new -x509 -days 3650 -nodes \
        -out "${SSL_DIR}/server.crt" \
        -keyout "${SSL_DIR}/server.key" \
        -subj "/CN=$(hostname)"
    chown postgres:postgres "${SSL_DIR}/server.crt" "${SSL_DIR}/server.key"
    chmod 600 "${SSL_DIR}/server.key"
fi

# Append snippets only once
SNIPPET_MARK="# --- BEGIN ${PROJECT} setup.sh snippet ---"
if ! grep -q "$SNIPPET_MARK" "$PGCONF"; then
    {
        echo
        echo "$SNIPPET_MARK"
        cat "$SCRIPT_DIR/postgresql/postgresql.conf.snippet"
        echo "# --- END ${PROJECT} setup.sh snippet ---"
    } >> "$PGCONF"
fi
if ! grep -q "$SNIPPET_MARK" "$PGHBA"; then
    {
        echo
        echo "$SNIPPET_MARK"
        sed "s/ocean_quest/${DBNAME}/g" \
            "$SCRIPT_DIR/postgresql/pg_hba.conf.snippet"
        echo "# --- END ${PROJECT} setup.sh snippet ---"
    } >> "$PGHBA"
fi

systemctl reload postgresql

# ── 6. Python venv + grant ETL on tables to RO role ────────────────────
if [ ! -d "$PROJECT_DIR/venv" ]; then
    echo "==> Creating Python venv..."
    sudo -u "$PROJECT" python3 -m venv "$PROJECT_DIR/venv"
fi
sudo -u "$PROJECT" "$PROJECT_DIR/venv/bin/pip" install --quiet --upgrade pip
sudo -u "$PROJECT" "$PROJECT_DIR/venv/bin/pip" install --quiet \
    -r "$PROJECT_DIR/requirements.txt"

echo "==> Initialising schema..."
sudo -u "$PROJECT" \
    --preserve-env=DATABASE_URL \
    bash -c "set -a; source $ETC_DIR/env; $PROJECT_DIR/venv/bin/python $PROJECT_DIR/db.py init"

# Grant SELECT on the now-existing tables to the RO role
sudo -u postgres psql -d "$DBNAME" <<SQL
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${RO_ROLE};
SQL

# ── 7. systemd units ──────────────────────────────────────────────────
echo "==> Installing systemd units..."
install -m 644 "$SCRIPT_DIR/${PROJECT}-fetch.service"     /etc/systemd/system/
install -m 644 "$SCRIPT_DIR/${PROJECT}-discover.service"  /etc/systemd/system/
install -m 644 "$SCRIPT_DIR/${PROJECT}-discover.timer"    /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now "${PROJECT}-fetch.service"
systemctl enable --now "${PROJECT}-discover.timer"

# ── 8. Firewall ────────────────────────────────────────────────────────
echo "==> Configuring UFW..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 5432/tcp
ufw --force enable

echo
echo "==================== Setup complete ===================="
echo "  Edit secrets:        sudo $EDITOR $ETC_DIR/env"
echo "  Restart fetch:       sudo systemctl restart ${PROJECT}-fetch"
echo "  Tail logs:           sudo journalctl -u ${PROJECT}-fetch -f"
echo "  DB shell:            sudo -u postgres psql $DBNAME"
echo "  Discovery timer:     systemctl list-timers ${PROJECT}-discover"
echo "========================================================"
